// Package webassets exposes the production Web workbench bundled into the
// Yuanshu Server binary. The dist directory is generated by the Web build and
// committed so ordinary Go builds do not require a Node.js toolchain.
package webassets

import (
	"embed"
	"io/fs"
)

//go:embed dist
var embedded embed.FS

// FS returns a read-only filesystem rooted at the Vite distribution.
func FS() (fs.FS, error) {
	return fs.Sub(embedded, "dist")
}
