// Code generated by scripts/protocol-v11.mjs; DO NOT EDIT.

package v11

const (
	CurrentVersion       = "1.1"
	ControlFrameMaxBytes = 256 * 1024
	EventFrameMaxBytes   = 1024 * 1024
)

type ControlType string

const (
	ControlDeviceSync         ControlType = "device.sync"
	ControlWorkspaceList      ControlType = "workspace.list"
	ControlAgentList          ControlType = "agent.list"
	ControlAgentRead          ControlType = "agent.read"
	ControlTaskList           ControlType = "task.list"
	ControlTaskRead           ControlType = "task.read"
	ControlTaskStart          ControlType = "task.start"
	ControlTaskResume         ControlType = "task.resume"
	ControlRunStart           ControlType = "run.start"
	ControlRunSteer           ControlType = "run.steer"
	ControlRunInterrupt       ControlType = "run.interrupt"
	ControlInteractionResolve ControlType = "interaction.resolve"
	ControlEventsReplay       ControlType = "events.replay"
	ControlSnapshotRequest    ControlType = "snapshot.request"
	ControlLeaseAcquire       ControlType = "lease.acquire"
	ControlLeaseRenew         ControlType = "lease.renew"
	ControlLeaseRelease       ControlType = "lease.release"
	ControlLeaseStatus        ControlType = "lease.status"
	ControlNotificationsList  ControlType = "notifications.list"
	ControlNotificationsRead  ControlType = "notifications.read"
	ControlConfigRead         ControlType = "config.read"
	ControlConfigUpdate       ControlType = "config.update"
)

var KnownControlTypes = []ControlType{
	ControlDeviceSync,
	ControlWorkspaceList,
	ControlAgentList,
	ControlAgentRead,
	ControlTaskList,
	ControlTaskRead,
	ControlTaskStart,
	ControlTaskResume,
	ControlRunStart,
	ControlRunSteer,
	ControlRunInterrupt,
	ControlInteractionResolve,
	ControlEventsReplay,
	ControlSnapshotRequest,
	ControlLeaseAcquire,
	ControlLeaseRenew,
	ControlLeaseRelease,
	ControlLeaseStatus,
	ControlNotificationsList,
	ControlNotificationsRead,
	ControlConfigRead,
	ControlConfigUpdate,
}

type EventType string

const (
	EventDeviceStatus              EventType = "device.status"
	EventRuntimeStatus             EventType = "runtime.status"
	EventAgentSnapshot             EventType = "agent.snapshot"
	EventAgentStatus               EventType = "agent.status"
	EventTaskSnapshot              EventType = "task.snapshot"
	EventTaskStarted               EventType = "task.started"
	EventTaskUpdated               EventType = "task.updated"
	EventRunStarted                EventType = "run.started"
	EventRunCompleted              EventType = "run.completed"
	EventRunFailed                 EventType = "run.failed"
	EventRunInterrupted            EventType = "run.interrupted"
	EventMessageDelta              EventType = "message.delta"
	EventMessageCompleted          EventType = "message.completed"
	EventReasoningSummaryDelta     EventType = "reasoning.summary.delta"
	EventReasoningSummaryCompleted EventType = "reasoning.summary.completed"
	EventPlanUpdated               EventType = "plan.updated"
	EventActivityStarted           EventType = "activity.started"
	EventActivityUpdated           EventType = "activity.updated"
	EventActivityCompleted         EventType = "activity.completed"
	EventInteractionRequested      EventType = "interaction.requested"
	EventInteractionResolved       EventType = "interaction.resolved"
	EventFileChanged               EventType = "file.changed"
	EventDiffUpdated               EventType = "diff.updated"
	EventControlResult             EventType = "control.result"
	EventLeaseChanged              EventType = "lease.changed"
	EventHistoryGap                EventType = "history.gap"
	EventError                     EventType = "error"
)

var KnownEventTypes = []EventType{
	EventDeviceStatus,
	EventRuntimeStatus,
	EventAgentSnapshot,
	EventAgentStatus,
	EventTaskSnapshot,
	EventTaskStarted,
	EventTaskUpdated,
	EventRunStarted,
	EventRunCompleted,
	EventRunFailed,
	EventRunInterrupted,
	EventMessageDelta,
	EventMessageCompleted,
	EventReasoningSummaryDelta,
	EventReasoningSummaryCompleted,
	EventPlanUpdated,
	EventActivityStarted,
	EventActivityUpdated,
	EventActivityCompleted,
	EventInteractionRequested,
	EventInteractionResolved,
	EventFileChanged,
	EventDiffUpdated,
	EventControlResult,
	EventLeaseChanged,
	EventHistoryGap,
	EventError,
}

type ErrorCode string

const (
	ErrorInvalidMessage      ErrorCode = "invalid_message"
	ErrorUnsupportedProtocol ErrorCode = "unsupported_protocol"
	ErrorUnsupportedControl  ErrorCode = "unsupported_control"
	ErrorUnauthorized        ErrorCode = "unauthorized"
	ErrorForbidden           ErrorCode = "forbidden"
	ErrorExpired             ErrorCode = "expired"
	ErrorReplay              ErrorCode = "replay"
	ErrorNotFound            ErrorCode = "not_found"
	ErrorConflict            ErrorCode = "conflict"
	ErrorRateLimited         ErrorCode = "rate_limited"
	ErrorPayloadTooLarge     ErrorCode = "payload_too_large"
	ErrorRuntimeUnavailable  ErrorCode = "runtime_unavailable"
	ErrorRuntimeFailed       ErrorCode = "runtime_failed"
	ErrorHistoryGap          ErrorCode = "history_gap"
	ErrorAmbiguous           ErrorCode = "ambiguous"
	ErrorInternal            ErrorCode = "internal"
)

type ControlResultStatus string

const (
	ControlResultReceived    ControlResultStatus = "received"
	ControlResultValidated   ControlResultStatus = "validated"
	ControlResultDispatching ControlResultStatus = "dispatching"
	ControlResultConfirmed   ControlResultStatus = "confirmed"
	ControlResultRejected    ControlResultStatus = "rejected"
	ControlResultAmbiguous   ControlResultStatus = "ambiguous"
)
