// Code generated by scripts/protocol.mjs from yuanshu-protocol.schema.json; DO NOT EDIT.

package v1

const (
	CurrentVersion       = "1.0"
	ControlFrameMaxBytes = 256 * 1024
	EventFrameMaxBytes   = 1024 * 1024
)

type ControlType string

const (
	ControlDeviceSync        ControlType = "device.sync"
	ControlWorkspaceList     ControlType = "workspace.list"
	ControlThreadList        ControlType = "thread.list"
	ControlThreadRead        ControlType = "thread.read"
	ControlThreadStart       ControlType = "thread.start"
	ControlThreadResume      ControlType = "thread.resume"
	ControlTurnStart         ControlType = "turn.start"
	ControlTurnSteer         ControlType = "turn.steer"
	ControlTurnInterrupt     ControlType = "turn.interrupt"
	ControlApprovalResolve   ControlType = "approval.resolve"
	ControlEventsReplay      ControlType = "events.replay"
	ControlSnapshotRequest   ControlType = "snapshot.request"
	ControlLeaseAcquire      ControlType = "lease.acquire"
	ControlLeaseRenew        ControlType = "lease.renew"
	ControlLeaseRelease      ControlType = "lease.release"
	ControlLeaseStatus       ControlType = "lease.status"
	ControlNotificationsList ControlType = "notifications.list"
	ControlNotificationsRead ControlType = "notifications.read"
	ControlConfigRead        ControlType = "config.read"
	ControlConfigUpdate      ControlType = "config.update"
)

var KnownControlTypes = []ControlType{
	ControlDeviceSync,
	ControlWorkspaceList,
	ControlThreadList,
	ControlThreadRead,
	ControlThreadStart,
	ControlThreadResume,
	ControlTurnStart,
	ControlTurnSteer,
	ControlTurnInterrupt,
	ControlApprovalResolve,
	ControlEventsReplay,
	ControlSnapshotRequest,
	ControlLeaseAcquire,
	ControlLeaseRenew,
	ControlLeaseRelease,
	ControlLeaseStatus,
	ControlNotificationsList,
	ControlNotificationsRead,
	ControlConfigRead,
	ControlConfigUpdate,
}

type EventType string

const (
	EventDeviceStatus          EventType = "device.status"
	EventRuntimeStatus         EventType = "runtime.status"
	EventThreadSnapshot        EventType = "thread.snapshot"
	EventThreadStarted         EventType = "thread.started"
	EventTurnStarted           EventType = "turn.started"
	EventTurnCompleted         EventType = "turn.completed"
	EventTurnFailed            EventType = "turn.failed"
	EventTurnInterrupted       EventType = "turn.interrupted"
	EventAgentMessageDelta     EventType = "agent.message.delta"
	EventAgentMessageCompleted EventType = "agent.message.completed"
	EventCommandStarted        EventType = "command.started"
	EventCommandOutputDelta    EventType = "command.output.delta"
	EventCommandCompleted      EventType = "command.completed"
	EventToolStarted           EventType = "tool.started"
	EventToolCompleted         EventType = "tool.completed"
	EventFileChanged           EventType = "file.changed"
	EventDiffUpdated           EventType = "diff.updated"
	EventApprovalRequested     EventType = "approval.requested"
	EventApprovalResolved      EventType = "approval.resolved"
	EventControlResult         EventType = "control.result"
	EventLeaseChanged          EventType = "lease.changed"
	EventHistoryGap            EventType = "history.gap"
	EventError                 EventType = "error"
)

var KnownEventTypes = []EventType{
	EventDeviceStatus,
	EventRuntimeStatus,
	EventThreadSnapshot,
	EventThreadStarted,
	EventTurnStarted,
	EventTurnCompleted,
	EventTurnFailed,
	EventTurnInterrupted,
	EventAgentMessageDelta,
	EventAgentMessageCompleted,
	EventCommandStarted,
	EventCommandOutputDelta,
	EventCommandCompleted,
	EventToolStarted,
	EventToolCompleted,
	EventFileChanged,
	EventDiffUpdated,
	EventApprovalRequested,
	EventApprovalResolved,
	EventControlResult,
	EventLeaseChanged,
	EventHistoryGap,
	EventError,
}

type ErrorCode string

const (
	ErrorInvalidMessage      ErrorCode = "invalid_message"
	ErrorUnsupportedProtocol ErrorCode = "unsupported_protocol"
	ErrorUnsupportedControl  ErrorCode = "unsupported_control"
	ErrorUnauthorized        ErrorCode = "unauthorized"
	ErrorForbidden           ErrorCode = "forbidden"
	ErrorExpired             ErrorCode = "expired"
	ErrorReplay              ErrorCode = "replay"
	ErrorNotFound            ErrorCode = "not_found"
	ErrorConflict            ErrorCode = "conflict"
	ErrorRateLimited         ErrorCode = "rate_limited"
	ErrorPayloadTooLarge     ErrorCode = "payload_too_large"
	ErrorRuntimeUnavailable  ErrorCode = "runtime_unavailable"
	ErrorRuntimeFailed       ErrorCode = "runtime_failed"
	ErrorHistoryGap          ErrorCode = "history_gap"
	ErrorAmbiguous           ErrorCode = "ambiguous"
	ErrorInternal            ErrorCode = "internal"
)

type ControlResultStatus string

const (
	ControlResultReceived    ControlResultStatus = "received"
	ControlResultValidated   ControlResultStatus = "validated"
	ControlResultDispatching ControlResultStatus = "dispatching"
	ControlResultConfirmed   ControlResultStatus = "confirmed"
	ControlResultRejected    ControlResultStatus = "rejected"
	ControlResultAmbiguous   ControlResultStatus = "ambiguous"
)
