// Code generated by scripts/protocol.mjs from yuanshu-protocol.schema.json; DO NOT EDIT.

package v1

const protocolSchemaJSON = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://yuanshu.ai/schemas/protocol/v1/yuanshu-protocol.schema.json",
  "title": "YuanshuMessage",
  "description": "Yuanshu Protocol v1 control and event envelope.",
  "oneOf": [
    { "$ref": "#/$defs/controlMessage" },
    { "$ref": "#/$defs/eventMessage" }
  ],
  "$defs": {
    "opaqueId": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "protocolVersion": {
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+$"
    },
    "sequence": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "logicalPath": {
      "type": "string",
      "minLength": 1,
      "maxLength": 4096,
      "pattern": "^(?!/)(?![A-Za-z]:)(?!.*(?:^|/)\\.\\.(?:/|$))(?!.*\\\\).+$"
    },
    "operationDigest": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{43}$"
    },
    "signer": {
      "type": "object",
      "required": ["clientId", "keyId"],
      "properties": {
        "clientId": { "$ref": "#/$defs/opaqueId" },
        "keyId": { "$ref": "#/$defs/opaqueId" }
      },
      "additionalProperties": false
    },
    "controlType": {
      "type": "string",
      "enum": [
        "device.sync",
        "workspace.list",
        "thread.list",
        "thread.read",
        "thread.start",
        "thread.resume",
        "turn.start",
        "turn.steer",
        "turn.interrupt",
        "approval.resolve",
        "events.replay",
        "snapshot.request",
        "lease.acquire",
        "lease.renew",
        "lease.release",
        "lease.status",
        "notifications.list",
        "notifications.read",
        "config.read",
        "config.update"
      ]
    },
    "eventType": {
      "type": "string",
      "enum": [
        "device.status",
        "runtime.status",
        "thread.snapshot",
        "thread.started",
        "turn.started",
        "turn.completed",
        "turn.failed",
        "turn.interrupted",
        "agent.message.delta",
        "agent.message.completed",
        "command.started",
        "command.output.delta",
        "command.completed",
        "tool.started",
        "tool.completed",
        "file.changed",
        "diff.updated",
        "approval.requested",
        "approval.resolved",
        "control.result",
        "lease.changed",
        "history.gap",
        "error"
      ]
    },
    "controlMessage": {
      "type": "object",
      "required": [
        "protocolVersion", "messageId", "type", "sentAt", "expiresAt",
        "ownerId", "nodeId", "streamId", "sequence", "correlationId",
        "nonce", "signer", "signature", "payload"
      ],
      "properties": {
        "protocolVersion": { "const": "1.0" },
        "messageId": { "$ref": "#/$defs/opaqueId" },
        "type": { "$ref": "#/$defs/controlType" },
        "sentAt": { "$ref": "#/$defs/timestamp" },
        "expiresAt": { "$ref": "#/$defs/timestamp" },
        "ownerId": { "$ref": "#/$defs/opaqueId" },
        "nodeId": { "$ref": "#/$defs/opaqueId" },
        "workspaceId": { "$ref": "#/$defs/opaqueId" },
        "threadId": { "$ref": "#/$defs/opaqueId" },
        "turnId": { "$ref": "#/$defs/opaqueId" },
        "itemId": { "$ref": "#/$defs/opaqueId" },
        "streamId": { "$ref": "#/$defs/opaqueId" },
        "sequence": { "$ref": "#/$defs/sequence" },
        "correlationId": { "$ref": "#/$defs/opaqueId" },
        "nonce": { "type": "string", "pattern": "^[A-Za-z0-9_-]{22}$" },
        "signer": { "$ref": "#/$defs/signer" },
        "signature": { "type": "string", "pattern": "^[A-Za-z0-9_-]{86}$" },
        "payload": { "type": "object" }
      },
      "additionalProperties": false,
      "allOf": [
        { "$ref": "#/$defs/controlPayloadRules" }
      ]
    },
    "eventMessage": {
      "type": "object",
      "required": [
        "protocolVersion", "messageId", "type", "sentAt", "ownerId",
        "nodeId", "streamId", "sequence", "correlationId", "payload"
      ],
      "properties": {
        "protocolVersion": {
          "type": "string",
          "pattern": "^1\\.[0-9]+$"
        },
        "messageId": { "$ref": "#/$defs/opaqueId" },
        "type": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128,
          "not": { "$ref": "#/$defs/controlType" }
        },
        "sentAt": { "$ref": "#/$defs/timestamp" },
        "ownerId": { "$ref": "#/$defs/opaqueId" },
        "nodeId": { "$ref": "#/$defs/opaqueId" },
        "workspaceId": { "$ref": "#/$defs/opaqueId" },
        "threadId": { "$ref": "#/$defs/opaqueId" },
        "turnId": { "$ref": "#/$defs/opaqueId" },
        "itemId": { "$ref": "#/$defs/opaqueId" },
        "streamId": { "$ref": "#/$defs/opaqueId" },
        "sequence": { "$ref": "#/$defs/sequence" },
        "correlationId": { "$ref": "#/$defs/opaqueId" },
        "payload": { "type": "object" }
      },
      "additionalProperties": false,
      "allOf": [
        { "$ref": "#/$defs/eventPayloadRules" }
      ]
    },
    "emptyControlPayload": {
      "type": "object",
      "additionalProperties": false
    },
    "listPayload": {
      "type": "object",
      "properties": {
        "cursor": { "type": "string", "minLength": 1, "maxLength": 512 },
        "limit": { "type": "integer", "minimum": 1, "maximum": 200 }
      },
      "additionalProperties": false
    },
    "threadReadPayload": {
      "type": "object",
      "properties": {
        "includeTurns": { "type": "boolean" },
        "includeDiffs": { "type": "boolean" },
        "diffPath": { "$ref": "#/$defs/logicalPath" },
        "maxDiffBytes": { "type": "integer", "minimum": 1, "maximum": 65536 }
      },
      "additionalProperties": false
    },
    "textInputPayload": {
      "type": "object",
      "required": ["input"],
      "properties": {
        "input": { "type": "string", "minLength": 1, "maxLength": 65536 }
      },
      "additionalProperties": false
    },
    "leaseProof": {
      "type": "object",
      "required": ["leaseId", "epoch"],
      "properties": {
        "leaseId": { "$ref": "#/$defs/opaqueId" },
        "epoch": { "$ref": "#/$defs/sequence" }
      },
      "additionalProperties": false
    },
    "turnTextPayload": {
      "type": "object",
      "required": ["input"],
      "properties": {
        "input": { "type": "string", "minLength": 1, "maxLength": 65536 },
        "lease": { "$ref": "#/$defs/leaseProof" }
      },
      "additionalProperties": false
    },
    "turnInterruptPayload": {
      "type": "object",
      "properties": { "lease": { "$ref": "#/$defs/leaseProof" } },
      "additionalProperties": false
    },
    "approvalResolvePayload": {
      "type": "object",
      "required": ["approvalId", "decision", "operationDigest"],
      "properties": {
        "approvalId": { "$ref": "#/$defs/opaqueId" },
        "decision": { "type": "string", "enum": ["accept", "decline"] },
        "operationDigest": { "$ref": "#/$defs/operationDigest" },
        "lease": { "$ref": "#/$defs/leaseProof" }
      },
      "additionalProperties": false
    },
    "eventsReplayPayload": {
      "type": "object",
      "required": ["afterSequence"],
      "properties": {
        "afterSequence": { "$ref": "#/$defs/sequence" }
      },
      "additionalProperties": false
    },
    "leaseAcquirePayload": {
      "type": "object",
      "properties": {
        "force": { "type": "boolean" },
        "expectedEpoch": { "$ref": "#/$defs/sequence" }
      },
      "additionalProperties": false
    },
    "leaseMutationPayload": {
      "type": "object",
      "required": ["leaseId", "epoch"],
      "properties": {
        "leaseId": { "$ref": "#/$defs/opaqueId" },
        "epoch": { "$ref": "#/$defs/sequence" }
      },
      "additionalProperties": false
    },
    "notificationReadPayload": {
      "type": "object",
      "required": ["notificationId"],
      "properties": { "notificationId": { "$ref": "#/$defs/opaqueId" } },
      "additionalProperties": false
    },
    "configReadPayload": {
      "type": "object",
      "additionalProperties": false
    },
    "workspaceConfigChange": {
      "type": "object",
      "required": ["id"],
      "properties": {
        "id": { "$ref": "#/$defs/opaqueId" },
        "displayName": { "type": "string", "minLength": 1, "maxLength": 128 },
        "permissionProfile": { "type": "string", "enum": ["read-only", "workspace-write"] },
        "allowNetwork": { "type": "boolean" }
      },
      "additionalProperties": false
    },
    "configUpdateChanges": {
      "type": "object",
      "properties": {
        "hostName": { "type": "string", "minLength": 1, "maxLength": 128 },
        "relayUrl": { "type": "string", "minLength": 1, "maxLength": 2048 },
        "proxyUrl": { "type": "string", "maxLength": 2048 },
        "connectTimeoutSeconds": { "type": "integer", "minimum": 1, "maximum": 120 },
        "eventsMaxAgeHours": { "type": "integer", "minimum": 1, "maximum": 720 },
        "eventsMaxSizeMiB": { "type": "integer", "minimum": 16, "maximum": 4096 },
        "workspaces": { "type": "array", "maxItems": 128, "items": { "$ref": "#/$defs/workspaceConfigChange" } }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "configUpdatePayload": {
      "type": "object",
      "required": ["baseRevision", "changes"],
      "properties": {
        "baseRevision": { "type": "string", "minLength": 1, "maxLength": 128 },
        "changes": { "$ref": "#/$defs/configUpdateChanges" }
      },
      "additionalProperties": false
    },
    "controlPayloadRules": {
      "allOf": [
        { "if": { "properties": { "type": { "const": "device.sync" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/emptyControlPayload" } } } },
        { "if": { "properties": { "type": { "const": "workspace.list" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/listPayload" } } } },
        { "if": { "properties": { "type": { "const": "thread.list" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/listPayload" } } } },
        { "if": { "properties": { "type": { "const": "thread.read" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/threadReadPayload" } } } },
        { "if": { "properties": { "type": { "const": "thread.start" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/textInputPayload" } } } },
        { "if": { "properties": { "type": { "const": "thread.resume" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/emptyControlPayload" } } } },
        { "if": { "properties": { "type": { "const": "turn.start" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/turnTextPayload" } } } },
        { "if": { "properties": { "type": { "const": "turn.steer" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/turnTextPayload" } } } },
        { "if": { "properties": { "type": { "const": "turn.interrupt" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/turnInterruptPayload" } } } },
        { "if": { "properties": { "type": { "const": "approval.resolve" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/approvalResolvePayload" } } } },
        { "if": { "properties": { "type": { "const": "events.replay" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/eventsReplayPayload" } } } },
        { "if": { "properties": { "type": { "const": "snapshot.request" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/emptyControlPayload" } } } },
        { "if": { "properties": { "type": { "const": "lease.acquire" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/leaseAcquirePayload" } } } },
        { "if": { "properties": { "type": { "const": "lease.renew" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/leaseMutationPayload" } } } },
        { "if": { "properties": { "type": { "const": "lease.release" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/leaseMutationPayload" } } } },
        { "if": { "properties": { "type": { "const": "lease.status" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/emptyControlPayload" } } } },
        { "if": { "properties": { "type": { "const": "notifications.list" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/listPayload" } } } },
        { "if": { "properties": { "type": { "const": "notifications.read" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/notificationReadPayload" } } } },
        { "if": { "properties": { "type": { "const": "config.read" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/configReadPayload" } } } },
        { "if": { "properties": { "type": { "const": "config.update" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/configUpdatePayload" } } } }
      ]
    },
    "statusPayload": {
      "type": "object",
      "required": ["status"],
      "properties": { "status": { "type": "string", "minLength": 1, "maxLength": 64 } },
      "additionalProperties": true
    },
    "historyState": {
      "type": "string",
      "enum": ["complete", "partial", "unavailable"]
    },
    "threadItemPayload": {
      "type": "object",
      "required": ["id", "kind", "status"],
      "properties": {
        "id": { "$ref": "#/$defs/opaqueId" },
        "kind": { "type": "string", "enum": ["user_message", "agent_message", "command", "command_output", "tool", "file_change", "diff", "error", "unknown"] },
        "status": { "type": "string", "maxLength": 64 },
        "text": { "type": "string", "maxLength": 65536 },
        "command": { "type": "string", "maxLength": 65536 },
        "output": { "type": "string", "maxLength": 262144 },
        "toolName": { "type": "string", "maxLength": 256 },
        "path": { "$ref": "#/$defs/logicalPath" },
        "changeType": { "type": "string", "enum": ["created", "modified", "deleted", "renamed"] },
        "diff": { "type": "string", "maxLength": 262144 },
        "totalBytes": { "type": "integer", "minimum": 0 },
        "digest": { "$ref": "#/$defs/operationDigest" },
        "exitCode": { "type": "integer" },
        "errorCode": { "$ref": "#/$defs/errorCode" },
        "errorMessage": { "type": "string", "maxLength": 4096 },
        "partial": { "type": "boolean" },
        "truncated": { "type": "boolean" }
      },
      "additionalProperties": true
    },
    "threadSummaryPayload": {
      "type": "object",
      "required": ["id", "status"],
      "properties": {
        "id": { "$ref": "#/$defs/opaqueId" },
        "status": { "type": "string", "maxLength": 64 },
        "title": { "type": "string", "maxLength": 4096 },
        "preview": { "type": "string", "maxLength": 65536 },
        "historyState": { "$ref": "#/$defs/historyState" },
        "createdAt": { "$ref": "#/$defs/timestamp" },
        "updatedAt": { "$ref": "#/$defs/timestamp" },
        "pendingApprovals": { "type": "integer", "minimum": 0 }
      },
      "additionalProperties": true
    },
    "turnSnapshotPayload": {
      "type": "object",
      "required": ["id", "status"],
      "properties": {
        "id": { "$ref": "#/$defs/opaqueId" },
        "status": { "type": "string", "maxLength": 64 },
        "historyState": { "$ref": "#/$defs/historyState" },
        "items": { "type": "array", "items": { "$ref": "#/$defs/threadItemPayload" } }
      },
      "additionalProperties": true
    },
    "approvalSummaryPayload": {
      "type": "object",
      "required": ["approvalId", "kind", "status"],
      "properties": {
        "approvalId": { "$ref": "#/$defs/opaqueId" },
        "kind": { "type": "string", "maxLength": 64 },
        "status": { "type": "string", "maxLength": 64 },
        "summary": { "type": "string", "maxLength": 4096 },
        "operationDigest": { "$ref": "#/$defs/operationDigest" }
      },
      "additionalProperties": true
    },
    "threadSnapshotPayload": {
      "type": "object",
      "required": ["status"],
      "properties": {
        "status": { "type": "string", "minLength": 1, "maxLength": 64 },
        "historyState": { "$ref": "#/$defs/historyState" },
        "title": { "type": "string", "maxLength": 4096 },
        "preview": { "type": "string", "maxLength": 65536 },
        "createdAt": { "$ref": "#/$defs/timestamp" },
        "updatedAt": { "$ref": "#/$defs/timestamp" },
        "threads": { "type": "array", "items": { "$ref": "#/$defs/threadSummaryPayload" } },
        "turns": { "type": "array", "items": { "$ref": "#/$defs/turnSnapshotPayload" } },
        "nextCursor": { "type": "string", "maxLength": 512 },
        "pendingApprovals": { "type": "array", "items": { "$ref": "#/$defs/approvalSummaryPayload" } },
        "latestSequence": { "$ref": "#/$defs/sequence" }
      },
      "additionalProperties": true
    },
    "lifecyclePayload": {
      "type": "object",
      "properties": { "status": { "type": "string", "minLength": 1, "maxLength": 64 } },
      "additionalProperties": true
    },
    "textPayload": {
      "type": "object",
      "required": ["text"],
      "properties": { "text": { "type": "string", "maxLength": 1048576 } },
      "additionalProperties": true
    },
    "commandPayload": {
      "type": "object",
      "required": ["commandId"],
      "properties": {
        "commandId": { "$ref": "#/$defs/opaqueId" },
        "displayText": { "type": "string", "maxLength": 4096 },
        "exitCode": { "type": "integer" }
      },
      "additionalProperties": true
    },
    "commandOutputPayload": {
      "type": "object",
      "required": ["commandId", "stream", "text"],
      "properties": {
        "commandId": { "$ref": "#/$defs/opaqueId" },
        "stream": { "type": "string", "enum": ["stdout", "stderr"] },
        "text": { "type": "string", "maxLength": 1048576 }
      },
      "additionalProperties": true
    },
    "toolPayload": {
      "type": "object",
      "required": ["toolName"],
      "properties": { "toolName": { "type": "string", "minLength": 1, "maxLength": 128 } },
      "additionalProperties": true
    },
    "fileChangedPayload": {
      "type": "object",
      "required": ["path", "changeType"],
      "properties": {
        "path": { "$ref": "#/$defs/logicalPath" },
        "changeType": { "type": "string", "enum": ["created", "modified", "deleted", "renamed"] },
        "totalBytes": { "type": "integer", "minimum": 0 },
        "digest": { "$ref": "#/$defs/operationDigest" },
        "truncated": { "type": "boolean" }
      },
      "additionalProperties": true
    },
    "diffUpdatedPayload": {
      "type": "object",
      "required": ["path", "diff"],
      "properties": {
        "path": { "$ref": "#/$defs/logicalPath" },
        "diff": { "type": "string", "maxLength": 1048576 },
        "totalBytes": { "type": "integer", "minimum": 0 },
        "digest": { "$ref": "#/$defs/operationDigest" },
        "truncated": { "type": "boolean" }
      },
      "additionalProperties": true
    },
    "approvalRequestedPayload": {
      "type": "object",
      "required": ["approvalId", "operationDigest", "kind"],
      "properties": {
        "approvalId": { "$ref": "#/$defs/opaqueId" },
        "operationDigest": { "$ref": "#/$defs/operationDigest" },
        "kind": { "type": "string", "minLength": 1, "maxLength": 64 },
        "summary": { "type": "string", "maxLength": 4096 }
      },
      "additionalProperties": true
    },
    "approvalResolvedPayload": {
      "type": "object",
      "required": ["approvalId", "decision"],
      "properties": {
        "approvalId": { "$ref": "#/$defs/opaqueId" },
        "decision": { "type": "string", "enum": ["accept", "decline"] }
      },
      "additionalProperties": true
    },
    "leaseChangedPayload": {
      "type": "object",
      "required": ["state", "epoch"],
      "properties": {
        "state": { "type": "string", "enum": ["held", "released", "expired"] },
        "leaseId": { "$ref": "#/$defs/opaqueId" },
        "holderClientId": { "$ref": "#/$defs/opaqueId" },
        "epoch": { "$ref": "#/$defs/sequence" },
        "expiresAt": { "$ref": "#/$defs/timestamp" },
        "reason": { "type": "string", "maxLength": 64 }
      },
      "additionalProperties": true
    },
    "controlResultPayload": {
      "type": "object",
      "required": ["status"],
      "properties": {
        "status": {
          "type": "string",
          "enum": ["received", "validated", "dispatching", "confirmed", "rejected", "ambiguous"]
        },
        "errorCode": { "$ref": "#/$defs/errorCode" },
        "message": { "type": "string", "maxLength": 4096 }
      },
      "additionalProperties": true
    },
    "historyGapPayload": {
      "type": "object",
      "required": ["afterSequence", "earliestSequence"],
      "properties": {
        "afterSequence": { "$ref": "#/$defs/sequence" },
        "earliestSequence": { "$ref": "#/$defs/sequence" }
      },
      "additionalProperties": true
    },
    "errorCode": {
      "type": "string",
      "enum": [
        "invalid_message", "unsupported_protocol", "unsupported_control",
        "unauthorized", "forbidden", "expired", "replay", "not_found",
        "conflict", "rate_limited", "payload_too_large", "runtime_unavailable",
        "runtime_failed", "history_gap", "ambiguous", "internal"
      ]
    },
    "errorPayload": {
      "type": "object",
      "required": ["code", "message"],
      "properties": {
        "code": { "$ref": "#/$defs/errorCode" },
        "message": { "type": "string", "minLength": 1, "maxLength": 4096 },
        "retryable": { "type": "boolean" }
      },
      "additionalProperties": true
    },
    "eventPayloadRules": {
      "allOf": [
        { "if": { "properties": { "type": { "const": "device.status" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/statusPayload" } } } },
        { "if": { "properties": { "type": { "const": "runtime.status" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/statusPayload" } } } },
        { "if": { "properties": { "type": { "const": "thread.snapshot" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/threadSnapshotPayload" } } } },
        { "if": { "properties": { "type": { "enum": ["thread.started", "turn.started", "turn.completed", "turn.failed", "turn.interrupted"] } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/lifecyclePayload" } } } },
        { "if": { "properties": { "type": { "enum": ["agent.message.delta", "agent.message.completed"] } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/textPayload" } } } },
        { "if": { "properties": { "type": { "enum": ["command.started", "command.completed"] } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/commandPayload" } } } },
        { "if": { "properties": { "type": { "const": "command.output.delta" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/commandOutputPayload" } } } },
        { "if": { "properties": { "type": { "enum": ["tool.started", "tool.completed"] } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/toolPayload" } } } },
        { "if": { "properties": { "type": { "const": "file.changed" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/fileChangedPayload" } } } },
        { "if": { "properties": { "type": { "const": "diff.updated" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/diffUpdatedPayload" } } } },
        { "if": { "properties": { "type": { "const": "approval.requested" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/approvalRequestedPayload" } } } },
        { "if": { "properties": { "type": { "const": "approval.resolved" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/approvalResolvedPayload" } } } },
        { "if": { "properties": { "type": { "const": "control.result" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/controlResultPayload" } } } },
        { "if": { "properties": { "type": { "const": "lease.changed" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/leaseChangedPayload" } } } },
        { "if": { "properties": { "type": { "const": "history.gap" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/historyGapPayload" } } } },
        { "if": { "properties": { "type": { "const": "error" } } }, "then": { "properties": { "payload": { "$ref": "#/$defs/errorPayload" } } } }
      ]
    }
  }
}
`
