// Code generated by scripts/status-catalog.mjs; DO NOT EDIT.
// Source SHA256: 9450dc84dda95e1ac1f170c74e4c762c75970df380ed117793b5e27e5169b367
package statuscatalog

type Entry struct {
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Action      string `json:"action"`
	Severity    string `json:"severity"`
	Retryable   bool   `json:"retryable"`
	SafeToRetry bool   `json:"safeToRetry"`
}

var entries = map[string]Entry{
	"online":                   {Code: "online", Title: "已在线", Description: "设备与远枢已建立安全连接。", Action: "可以继续查看或执行任务。", Severity: "success", Retryable: false, SafeToRetry: false},
	"offline":                  {Code: "offline", Title: "设备离线", Description: "当前无法连接到设备，但本机任务可能仍在运行。", Action: "检查设备电源、网络和 Node 状态。", Severity: "warning", Retryable: true, SafeToRetry: true},
	"reconnecting":             {Code: "reconnecting", Title: "正在重连", Description: "连接中断后正在安全恢复会话和事件。", Action: "等待自动恢复；不要重复提交任务操作。", Severity: "info", Retryable: true, SafeToRetry: true},
	"runtime_unavailable":      {Code: "runtime_unavailable", Title: "Codex 暂不可用", Description: "Node 在线，但本机 Codex Runtime 未就绪。", Action: "在 Node 本机运行 doctor 并检查 Codex。", Severity: "danger", Retryable: true, SafeToRetry: true},
	"runtime_unverified":       {Code: "runtime_unverified", Title: "Codex 版本未验证", Description: "当前版本不在公开验证矩阵中，但不会被阻止。", Action: "可继续尝试；如有异常请附脱敏诊断。", Severity: "warning", Retryable: false, SafeToRetry: false},
	"history_gap":              {Code: "history_gap", Title: "部分历史缺失", Description: "本地事件保留期内无法恢复连续历史。", Action: "读取 Thread 快照并确认当前任务状态。", Severity: "warning", Retryable: true, SafeToRetry: true},
	"lease_occupied":           {Code: "lease_occupied", Title: "控制权被占用", Description: "另一个控制端正在操作此任务。", Action: "保持只读，或确认影响后显式接管。", Severity: "warning", Retryable: false, SafeToRetry: false},
	"lease_lost":               {Code: "lease_lost", Title: "控制权已丢失", Description: "租约已被释放、过期或被其他控制端接管。", Action: "重新读取状态后再决定是否获取控制权。", Severity: "danger", Retryable: true, SafeToRetry: true},
	"lease_expired":            {Code: "lease_expired", Title: "控制权已过期", Description: "当前租约已超过有效期。", Action: "重新获取控制权后再执行变更。", Severity: "warning", Retryable: true, SafeToRetry: true},
	"approval_expired":         {Code: "approval_expired", Title: "审批已过期", Description: "审批对象或有效期已变化，不能继续处理。", Action: "等待 Node 产生新的审批请求。", Severity: "warning", Retryable: false, SafeToRetry: false},
	"approval_ambiguous":       {Code: "approval_ambiguous", Title: "审批结果待确认", Description: "连接中断时无法确认审批是否已执行。", Action: "先恢复事件并读取快照，不要重复审批。", Severity: "danger", Retryable: false, SafeToRetry: false},
	"operation_unknown":        {Code: "operation_unknown", Title: "操作结果未知", Description: "请求已发送，但尚未获得可信执行结果。", Action: "等待事件恢复后确认，不要自动重试。", Severity: "warning", Retryable: false, SafeToRetry: false},
	"config_pending":           {Code: "config_pending", Title: "配置等待本机确认", Description: "安全边界变更尚未在 Node 本机批准。", Action: "在本机控制中心查看完整安全摘要。", Severity: "warning", Retryable: false, SafeToRetry: false},
	"config_rejected":          {Code: "config_rejected", Title: "配置变更已拒绝", Description: "本机用户拒绝了待确认变更。", Action: "重新读取配置后再提交新的变更。", Severity: "info", Retryable: true, SafeToRetry: true},
	"config_failed":            {Code: "config_failed", Title: "配置应用失败", Description: "Node 保留了上一份有效配置。", Action: "查看本机脱敏诊断并修正配置。", Severity: "danger", Retryable: true, SafeToRetry: true},
	"certificate_expiring_30d": {Code: "certificate_expiring_30d", Title: "证书将在 30 天内到期", Description: "Relay TLS 证书需要计划更新。", Action: "在 Server 本机准备并验证新证书。", Severity: "warning", Retryable: false, SafeToRetry: false},
	"certificate_expiring_14d": {Code: "certificate_expiring_14d", Title: "证书将在 14 天内到期", Description: "Relay TLS 证书即将影响设备连接。", Action: "尽快在 Server 本机更新证书。", Severity: "warning", Retryable: false, SafeToRetry: false},
	"certificate_expiring_7d":  {Code: "certificate_expiring_7d", Title: "证书将在 7 天内到期", Description: "证书到期后浏览器与 Node 将拒绝连接。", Action: "立即在 Server 本机更新并验证证书。", Severity: "danger", Retryable: false, SafeToRetry: false},
	"certificate_expired":      {Code: "certificate_expired", Title: "证书已过期", Description: "TLS 身份已失效，远程连接应被拒绝。", Action: "在 Server 本机更换证书后重新启动。", Severity: "danger", Retryable: false, SafeToRetry: false},
	"backup_unavailable":       {Code: "backup_unavailable", Title: "没有可用备份", Description: "尚未发现经过验证的 Server 数据库备份。", Action: "在 Server 本机运行 yuanshu server backup。", Severity: "warning", Retryable: true, SafeToRetry: true},
	"backup_invalid":           {Code: "backup_invalid", Title: "最近备份无效", Description: "最近备份未通过格式、校验和或数据库检查。", Action: "不要恢复该文件；在 Server 本机重新备份。", Severity: "danger", Retryable: true, SafeToRetry: true},
	"setup_required":           {Code: "setup_required", Title: "需要完成设置", Description: "Node 还没有可用的本机配置。", Action: "打开本机控制中心完成首次设置。", Severity: "warning", Retryable: true, SafeToRetry: true},
}

func Lookup(code string) (Entry, bool) { value, ok := entries[code]; return value, ok }
func All() []Entry {
	result := make([]Entry, 0, len(entries))
	for _, value := range entries {
		result = append(result, value)
	}
	return result
}
