import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const locales = ["zh-CN", "en-US"];
const sourcePaths = Object.fromEntries(locales.map((locale) => [locale, path.join(root, "locales", `${locale}.json`)]));
const outputs = [
  path.join(root, "web", "src", "i18n", "catalog.generated.ts"),
  path.join(root, "node-web", "src", "i18n", "catalog.generated.ts"),
];
const jsOutput = path.join(root, "internal", "server", "pairing-web", "catalog.generated.js");
const goOutput = path.join(root, "internal", "i18n", "catalog_generated.go");

async function catalogs() {
  const entries = await Promise.all(locales.map(async (locale) => [locale, JSON.parse(await readFile(sourcePaths[locale], "utf8"))]));
  return Object.fromEntries(entries);
}

function assertCatalogs(values) {
  const baseline = Object.keys(values[locales[0]]).sort();
  if (!baseline.length) throw new Error("locale catalog is empty");
  for (const locale of locales) {
    const keys = Object.keys(values[locale]).sort();
    if (JSON.stringify(keys) !== JSON.stringify(baseline)) throw new Error(`${locale} locale keys do not match`);
    for (const key of keys) {
      const value = values[locale][key];
      if (typeof value !== "string" || !value.trim()) throw new Error(`${locale}:${key} is empty`);
      const placeholders = [...value.matchAll(/\{([A-Za-z][A-Za-z0-9]*)\}/g)].map((match) => match[1]).sort();
      const reference = [...values[locales[0]][key].matchAll(/\{([A-Za-z][A-Za-z0-9]*)\}/g)].map((match) => match[1]).sort();
      if (JSON.stringify(placeholders) !== JSON.stringify(reference)) throw new Error(`${locale}:${key} placeholders do not match`);
    }
  }
}

function tsSource(values) {
  return `// Code generated by scripts/i18n.mjs; DO NOT EDIT.\nexport const catalogs = ${JSON.stringify(values, null, 2)} as const;\nexport type Locale = keyof typeof catalogs;\nexport type MessageKey = keyof typeof catalogs[\"zh-CN\"];\n`;
}

function jsSource(values) {
  return `// Code generated by scripts/i18n.mjs; DO NOT EDIT.\nexport const catalogs = Object.freeze(${JSON.stringify(values, null, 2)});\n`;
}

function goSource(values) {
  const quote = (value) => JSON.stringify(value).replaceAll("<", "\\u003c").replaceAll(">", "\\u003e").replaceAll("&", "\\u0026");
  const maps = locales.map((locale) => {
    const entries = Object.entries(values[locale]);
    const width = Math.max(...entries.map(([key]) => quote(key).length));
    return `\t${quote(locale)}: {\n${entries.map(([key, value]) => `\t\t${`${quote(key)}:`.padEnd(width + 1)} ${quote(value)},`).join("\n")}\n\t},`;
  }).join("\n");
  return `// Code generated by scripts/i18n.mjs; DO NOT EDIT.\npackage i18n\n\nvar Catalogs = map[string]map[string]string{\n${maps}\n}\n`;
}

async function generate(values) {
  const ts = tsSource(values);
  for (const output of [...outputs, jsOutput, goOutput]) await mkdir(path.dirname(output), { recursive: true });
  for (const output of outputs) await writeFile(output, ts);
  await writeFile(jsOutput, jsSource(values));
  await writeFile(goOutput, goSource(values));
}

async function checkGenerated(values) {
  const expected = new Map([
    ...outputs.map((output) => [output, tsSource(values)]),
    [jsOutput, jsSource(values)],
    [goOutput, goSource(values)],
  ]);
  for (const [output, content] of expected) {
    const current = await readFile(output, "utf8").catch(() => "");
    if (current !== content) throw new Error(`${path.relative(root, output)} is stale; run pnpm i18n:generate`);
  }
}

const command = process.argv[2] ?? "check";
const values = await catalogs();
assertCatalogs(values);
if (command === "generate") await generate(values);
else if (command === "check") await checkGenerated(values);
else throw new Error(`unknown i18n command: ${command}`);
