import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schema = join(root, "schemas", "yuanshu", "v1", "yuanshu-protocol.schema.json");
const quicktype = join(root, "node_modules", "quicktype", "dist", "index.js");
const quicktypeOutputs = [
  {
    relative: join("internal", "protocol", "v1", "types.generated.go"),
    args: ["--lang", "go", "--package", "v1", "--just-types-and-package", "--no-date-times", "--no-uuids"],
  },
  {
    relative: join("web", "src", "protocol", "v1", "types.generated.ts"),
    args: ["--lang", "typescript", "--just-types", "--readonly", "--prefer-unions", "--no-date-times", "--no-uuids"],
  },
];
const generatedOutputs = [
  ...quicktypeOutputs,
  { relative: join("internal", "protocol", "v1", "catalog.generated.go") },
  { relative: join("internal", "protocol", "v1", "schema.generated.go") },
  { relative: join("web", "src", "protocol", "v1", "catalog.generated.ts") },
];

function fail(message) {
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
}

async function generateInto(destination) {
  for (const output of quicktypeOutputs) {
    const target = join(destination, output.relative);
    await mkdir(dirname(target), { recursive: true });
    const result = spawnSync(process.execPath, [
      quicktype,
      "--src-lang", "schema",
      "--src", schema,
      "--top-level", "YuanshuMessage",
      "--alphabetize-properties",
      "--telemetry", "disable",
      ...output.args,
      "--out", target,
    ], { cwd: root, encoding: "utf8" });
    if (result.status !== 0) {
      throw new Error(`quicktype failed for ${output.relative}: ${result.stderr || result.stdout}`);
    }
  }

  const schemaBytes = await readFile(schema);
  const schemaDocument = JSON.parse(schemaBytes.toString("utf8"));
  await writeCatalogs(destination, schemaDocument);
  await writeEmbeddedSchema(destination, schemaBytes);
  const metadata = {
    protocolVersion: "1.0",
    schemaDraft: "https://json-schema.org/draft/2020-12/schema",
    schemaFile: "yuanshu-protocol.schema.json",
    schemaSha256: createHash("sha256").update(schemaBytes).digest("hex"),
    generator: "quicktype@26.0.0",
    generatedTargets: generatedOutputs.map((output) => output.relative.replaceAll("\\", "/")),
    frameLimits: { control: 262144, event: 1048576 },
  };
  const metadataPath = join(destination, "schemas", "yuanshu", "v1", "metadata.json");
  await mkdir(dirname(metadataPath), { recursive: true });
  await writeFile(metadataPath, `${JSON.stringify(metadata, null, 2)}\n`, "utf8");
}

async function writeEmbeddedSchema(destination, schemaBytes) {
  const schemaText = schemaBytes.toString("utf8");
  if (schemaText.includes("`")) {
    throw new Error("protocol schema cannot be embedded in a Go raw string containing a backtick");
  }
  const go = "// Code generated by scripts/protocol.mjs from yuanshu-protocol.schema.json; DO NOT EDIT.\n\n" +
    "package v1\n\n" +
    "const protocolSchemaJSON = `" + schemaText + "`\n";
  const goPath = join(destination, "internal", "protocol", "v1", "schema.generated.go");
  await mkdir(dirname(goPath), { recursive: true });
  await writeFile(goPath, go, "utf8");
  const formatted = spawnSync("gofmt", ["-w", goPath], { cwd: root, encoding: "utf8" });
  if (formatted.status !== 0) {
    throw new Error(`gofmt failed for embedded schema: ${formatted.stderr || formatted.stdout}`);
  }
}

function pascalCase(value) {
  return value.split(/[^A-Za-z0-9]+/).filter(Boolean).map((part) => `${part[0].toUpperCase()}${part.slice(1)}`).join("");
}

async function writeCatalogs(destination, document) {
  const controls = document.$defs.controlType.enum;
  const events = document.$defs.eventType.enum;
  const errors = document.$defs.errorCode.enum;
  const states = document.$defs.controlResultPayload.properties.status.enum;
  const goConstants = (prefix, type, values) => values.map((value) => `\t${prefix}${pascalCase(value)} ${type} = ${JSON.stringify(value)}`).join("\n");
  const go = `// Code generated by scripts/protocol.mjs from yuanshu-protocol.schema.json; DO NOT EDIT.\n\npackage v1\n\nconst (\n\tCurrentVersion = "1.0"\n\tControlFrameMaxBytes = 256 * 1024\n\tEventFrameMaxBytes = 1024 * 1024\n)\n\ntype ControlType string\n\nconst (\n${goConstants("Control", "ControlType", controls)}\n)\n\nvar KnownControlTypes = []ControlType{\n${controls.map((value) => `\tControl${pascalCase(value)},`).join("\n")}\n}\n\ntype EventType string\n\nconst (\n${goConstants("Event", "EventType", events)}\n)\n\nvar KnownEventTypes = []EventType{\n${events.map((value) => `\tEvent${pascalCase(value)},`).join("\n")}\n}\n\ntype ErrorCode string\n\nconst (\n${goConstants("Error", "ErrorCode", errors)}\n)\n\ntype ControlResultStatus string\n\nconst (\n${goConstants("ControlResult", "ControlResultStatus", states)}\n)\n`;
  const ts = `// Code generated by scripts/protocol.mjs from yuanshu-protocol.schema.json; DO NOT EDIT.\n\nexport const CURRENT_VERSION = "1.0" as const;\nexport const CONTROL_FRAME_MAX_BYTES = 256 * 1024;\nexport const EVENT_FRAME_MAX_BYTES = 1024 * 1024;\n\nexport const KNOWN_CONTROL_TYPES = ${JSON.stringify(controls, null, 2)} as const;\nexport type ControlType = (typeof KNOWN_CONTROL_TYPES)[number];\n\nexport const KNOWN_EVENT_TYPES = ${JSON.stringify(events, null, 2)} as const;\nexport type EventType = (typeof KNOWN_EVENT_TYPES)[number];\n\nexport const ERROR_CODES = ${JSON.stringify(errors, null, 2)} as const;\nexport type ErrorCode = (typeof ERROR_CODES)[number];\n\nexport const CONTROL_RESULT_STATES = ${JSON.stringify(states, null, 2)} as const;\nexport type ControlResultStatus = (typeof CONTROL_RESULT_STATES)[number];\n`;
  const goPath = join(destination, "internal", "protocol", "v1", "catalog.generated.go");
  const tsPath = join(destination, "web", "src", "protocol", "v1", "catalog.generated.ts");
  await mkdir(dirname(goPath), { recursive: true });
  await mkdir(dirname(tsPath), { recursive: true });
  await writeFile(goPath, go, "utf8");
  await writeFile(tsPath, ts, "utf8");
  const formatted = spawnSync("gofmt", ["-w", goPath], { cwd: root, encoding: "utf8" });
  if (formatted.status !== 0) {
    throw new Error(`gofmt failed for generated catalog: ${formatted.stderr || formatted.stdout}`);
  }
}

async function compare(generatedRoot) {
  const paths = [...generatedOutputs.map((output) => output.relative), join("schemas", "yuanshu", "v1", "metadata.json")];
  let different = false;
  for (const relative of paths) {
    const expected = join(root, relative);
    const actual = join(generatedRoot, relative);
    if (!existsSync(expected)) {
      fail(`missing generated file: ${relative}`);
      different = true;
      continue;
    }
    const [expectedBytes, actualBytes] = await Promise.all([readFile(expected), readFile(actual)]);
    if (!expectedBytes.equals(actualBytes)) {
      fail(`generated file is stale: ${relative}`);
      different = true;
    }
  }
  if (different) process.exitCode = 1;
}

const mode = process.argv[2];
if (mode !== "generate" && mode !== "check") {
  fail("usage: node scripts/protocol.mjs <generate|check>");
} else if (!existsSync(quicktype)) {
  fail("quicktype is not installed; run pnpm install first");
} else if (mode === "generate") {
  const temp = await mkdtemp(join(tmpdir(), "yuanshu-protocol-"));
  try {
    await generateInto(temp);
    for (const output of generatedOutputs) {
      const target = join(root, output.relative);
      await mkdir(dirname(target), { recursive: true });
      await copyFile(join(temp, output.relative), target);
    }
    await copyFile(
      join(temp, "schemas", "yuanshu", "v1", "metadata.json"),
      join(root, "schemas", "yuanshu", "v1", "metadata.json"),
    );
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
} else {
  const temp = await mkdtemp(join(tmpdir(), "yuanshu-protocol-check-"));
  try {
    await generateInto(temp);
    await compare(temp);
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
}
