import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schema = join(root, "schemas", "yuanshu", "v1.1", "yuanshu-protocol.schema.json");
const quicktype = join(root, "node_modules", "quicktype", "dist", "index.js");
const outputs = [
  join("internal", "protocol", "v11", "types.generated.go"),
  join("internal", "protocol", "v11", "catalog.generated.go"),
  join("internal", "protocol", "v11", "schema.generated.go"),
  join("web", "src", "protocol", "v11", "types.generated.ts"),
  join("web", "src", "protocol", "v11", "catalog.generated.ts"),
];

const fail = (message) => { process.stderr.write(`${message}\n`); process.exitCode = 1; };
const pascalCase = (value) => value.split(/[^A-Za-z0-9]+/).filter(Boolean).map((part) => `${part[0].toUpperCase()}${part.slice(1)}`).join("");

async function generate(destination) {
  const goTypes = join(destination, outputs[0]);
  const tsTypes = join(destination, outputs[3]);
  await mkdir(dirname(goTypes), { recursive: true });
  await mkdir(dirname(tsTypes), { recursive: true });
  for (const [target, args] of [
    [goTypes, ["--lang", "go", "--package", "v11", "--just-types-and-package", "--no-date-times", "--no-uuids"]],
    [tsTypes, ["--lang", "typescript", "--just-types", "--readonly", "--prefer-unions", "--no-date-times", "--no-uuids"]],
  ]) {
    const result = spawnSync(process.execPath, [quicktype, "--src-lang", "schema", "--src", schema, "--top-level", "YuanshuMessage", "--alphabetize-properties", "--telemetry", "disable", ...args, "--out", target], { cwd: root, encoding: "utf8" });
    if (result.status !== 0) throw new Error(result.stderr || result.stdout);
  }
  const schemaBytes = await readFile(schema);
  const document = JSON.parse(schemaBytes.toString("utf8"));
  await writeCatalogs(destination, document);
  const schemaText = schemaBytes.toString("utf8");
  if (schemaText.includes("`")) throw new Error("protocol schema cannot contain a backtick");
  const schemaGo = `// Code generated by scripts/protocol-v11.mjs; DO NOT EDIT.\n\npackage v11\n\nconst protocolSchemaJSON = \`${schemaText}\`\n`;
  await writeFile(join(destination, outputs[2]), schemaGo);
  const metadata = {
    protocolVersion: "1.1", schemaDraft: "https://json-schema.org/draft/2020-12/schema",
    schemaFile: "yuanshu-protocol.schema.json", schemaSha256: createHash("sha256").update(schemaBytes).digest("hex"),
    generator: "quicktype@26.0.0", generatedTargets: outputs.map((item) => item.replaceAll("\\", "/")),
    frameLimits: { control: 262144, event: 1048576 },
  };
  const metadataPath = join(destination, "schemas", "yuanshu", "v1.1", "metadata.json");
  await mkdir(dirname(metadataPath), { recursive: true });
  await writeFile(metadataPath, `${JSON.stringify(metadata, null, 2)}\n`);
  for (const path of outputs.filter((item) => item.endsWith(".go"))) {
    const result = spawnSync("gofmt", ["-w", join(destination, path)], { cwd: root, encoding: "utf8" });
    if (result.status !== 0) throw new Error(result.stderr || result.stdout);
  }
}

async function writeCatalogs(destination, document) {
  const controls = document.$defs.controlType.enum;
  const events = document.$defs.eventType.enum;
  const errors = document.$defs.errorCode.enum;
  const states = document.$defs.controlResultPayload.properties.status.enum;
  const constants = (prefix, type, values) => values.map((value) => `\t${prefix}${pascalCase(value)} ${type} = ${JSON.stringify(value)}`).join("\n");
  const go = `// Code generated by scripts/protocol-v11.mjs; DO NOT EDIT.\n\npackage v11\n\nconst (\n\tCurrentVersion = "1.1"\n\tControlFrameMaxBytes = 256 * 1024\n\tEventFrameMaxBytes = 1024 * 1024\n)\n\ntype ControlType string\n\nconst (\n${constants("Control", "ControlType", controls)}\n)\n\nvar KnownControlTypes = []ControlType{\n${controls.map((value) => `\tControl${pascalCase(value)},`).join("\n")}\n}\n\ntype EventType string\n\nconst (\n${constants("Event", "EventType", events)}\n)\n\nvar KnownEventTypes = []EventType{\n${events.map((value) => `\tEvent${pascalCase(value)},`).join("\n")}\n}\n\ntype ErrorCode string\n\nconst (\n${constants("Error", "ErrorCode", errors)}\n)\n\ntype ControlResultStatus string\n\nconst (\n${constants("ControlResult", "ControlResultStatus", states)}\n)\n`;
  const ts = `// Code generated by scripts/protocol-v11.mjs; DO NOT EDIT.\n\nexport const CURRENT_VERSION = "1.1" as const;\nexport const CONTROL_FRAME_MAX_BYTES = 256 * 1024;\nexport const EVENT_FRAME_MAX_BYTES = 1024 * 1024;\n\nexport const KNOWN_CONTROL_TYPES = ${JSON.stringify(controls, null, 2)} as const;\nexport type ControlType = (typeof KNOWN_CONTROL_TYPES)[number];\n\nexport const KNOWN_EVENT_TYPES = ${JSON.stringify(events, null, 2)} as const;\nexport type EventType = (typeof KNOWN_EVENT_TYPES)[number];\n\nexport const ERROR_CODES = ${JSON.stringify(errors, null, 2)} as const;\nexport type ErrorCode = (typeof ERROR_CODES)[number];\n\nexport const CONTROL_RESULT_STATES = ${JSON.stringify(states, null, 2)} as const;\nexport type ControlResultStatus = (typeof CONTROL_RESULT_STATES)[number];\n`;
  await mkdir(dirname(join(destination, outputs[1])), { recursive: true });
  await mkdir(dirname(join(destination, outputs[4])), { recursive: true });
  await writeFile(join(destination, outputs[1]), go);
  await writeFile(join(destination, outputs[4]), ts);
}

async function compare(temp) {
  for (const path of [...outputs, join("schemas", "yuanshu", "v1.1", "metadata.json")]) {
    const expected = join(root, path);
    const actual = join(temp, path);
    if (!existsSync(expected) || !(await readFile(expected)).equals(await readFile(actual))) fail(`generated file is stale: ${path}`);
  }
}

const mode = process.argv[2];
if (!existsSync(quicktype)) fail("quicktype is not installed; run pnpm install first");
else if (mode !== "generate" && mode !== "check") fail("usage: node scripts/protocol-v11.mjs <generate|check>");
else {
  const temp = await mkdtemp(join(tmpdir(), "yuanshu-protocol-v11-"));
  try {
    await generate(temp);
    if (mode === "check") await compare(temp);
    else {
      for (const path of outputs) {
        await mkdir(dirname(join(root, path)), { recursive: true });
        await copyFile(join(temp, path), join(root, path));
      }
      await copyFile(join(temp, "schemas", "yuanshu", "v1.1", "metadata.json"), join(root, "schemas", "yuanshu", "v1.1", "metadata.json"));
    }
  } finally { await rm(temp, { recursive: true, force: true }); }
}
