import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const sourceRaw = await readFile(resolve(root, "status/catalog.json"), "utf8");
const source = JSON.parse(sourceRaw);
const sourceHash = createHash("sha256").update(sourceRaw).digest("hex");
const codes = new Set();
for (const item of source) {
  if (!item.code || codes.has(item.code) || !["success", "info", "warning", "danger"].includes(item.severity)) throw new Error(`invalid status catalog entry: ${item.code}`);
  codes.add(item.code);
}

const go = `// Code generated by scripts/status-catalog.mjs; DO NOT EDIT.\n// Source SHA256: ${sourceHash}\npackage statuscatalog\n\ntype Entry struct {\n\tCode string \`json:"code"\`\n\tTitle string \`json:"title"\`\n\tDescription string \`json:"description"\`\n\tAction string \`json:"action"\`\n\tSeverity string \`json:"severity"\`\n\tRetryable bool \`json:"retryable"\`\n\tSafeToRetry bool \`json:"safeToRetry"\`\n}\n\nvar entries = map[string]Entry{\n${source.map((item) => `\t${JSON.stringify(item.code)}: {Code: ${JSON.stringify(item.code)}, Title: ${JSON.stringify(item.title)}, Description: ${JSON.stringify(item.description)}, Action: ${JSON.stringify(item.action)}, Severity: ${JSON.stringify(item.severity)}, Retryable: ${item.retryable}, SafeToRetry: ${item.safeToRetry}},`).join("\n")}\n}\n\nfunc Lookup(code string) (Entry, bool) { value, ok := entries[code]; return value, ok }\nfunc All() []Entry { result := make([]Entry, 0, len(entries)); for _, value := range entries { result = append(result, value) }; return result }\n`;
const ts = `// Code generated by scripts/status-catalog.mjs; DO NOT EDIT.\nexport type MachineStatus = { code: string; title: string; description: string; action: string; severity: "success" | "info" | "warning" | "danger"; retryable: boolean; safeToRetry: boolean };\nexport const machineStatuses: Record<string, MachineStatus> = ${JSON.stringify(Object.fromEntries(source.map((item) => [item.code, item])), null, 2)};\nexport function machineStatus(code: string): MachineStatus | undefined { return machineStatuses[code]; }\n`;
const targets = [
  ["internal/statuscatalog/catalog_generated.go", go],
  ["web/src/status/catalog.generated.ts", ts],
  ["node-web/src/status/catalog.generated.ts", ts],
];
const check = process.argv[2] === "check";
for (const [path, content] of targets) {
  const absolute = resolve(root, path);
  if (check) {
    const current = await readFile(absolute, "utf8").catch(() => "");
    if (path.endsWith(".go")) {
      if (!current.includes(`// Source SHA256: ${sourceHash}`)) throw new Error(`${path} is stale; run status:generate`);
    } else if (current !== content) throw new Error(`${path} is stale; run status:generate`);
  } else {
    await writeFile(absolute, content);
  }
}
