// Code generated by scripts/protocol.mjs from yuanshu-protocol.schema.json; DO NOT EDIT.

export const CURRENT_VERSION = "1.0" as const;
export const CONTROL_FRAME_MAX_BYTES = 256 * 1024;
export const EVENT_FRAME_MAX_BYTES = 1024 * 1024;

export const KNOWN_CONTROL_TYPES = [
  "device.sync",
  "workspace.list",
  "thread.list",
  "thread.read",
  "thread.start",
  "thread.resume",
  "turn.start",
  "turn.steer",
  "turn.interrupt",
  "approval.resolve",
  "events.replay",
  "snapshot.request"
] as const;
export type ControlType = (typeof KNOWN_CONTROL_TYPES)[number];

export const KNOWN_EVENT_TYPES = [
  "device.status",
  "runtime.status",
  "thread.snapshot",
  "thread.started",
  "turn.started",
  "turn.completed",
  "turn.failed",
  "turn.interrupted",
  "agent.message.delta",
  "agent.message.completed",
  "command.started",
  "command.output.delta",
  "command.completed",
  "tool.started",
  "tool.completed",
  "file.changed",
  "diff.updated",
  "approval.requested",
  "approval.resolved",
  "control.result",
  "history.gap",
  "error"
] as const;
export type EventType = (typeof KNOWN_EVENT_TYPES)[number];

export const ERROR_CODES = [
  "invalid_message",
  "unsupported_protocol",
  "unsupported_control",
  "unauthorized",
  "forbidden",
  "expired",
  "replay",
  "not_found",
  "conflict",
  "rate_limited",
  "payload_too_large",
  "runtime_unavailable",
  "runtime_failed",
  "history_gap",
  "ambiguous",
  "internal"
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export const CONTROL_RESULT_STATES = [
  "received",
  "validated",
  "dispatching",
  "confirmed",
  "rejected",
  "ambiguous"
] as const;
export type ControlResultStatus = (typeof CONTROL_RESULT_STATES)[number];
