// Code generated by scripts/protocol-v11.mjs; DO NOT EDIT.

export const CURRENT_VERSION = "1.1" as const;
export const CONTROL_FRAME_MAX_BYTES = 256 * 1024;
export const EVENT_FRAME_MAX_BYTES = 1024 * 1024;

export const KNOWN_CONTROL_TYPES = [
  "device.sync",
  "workspace.list",
  "agent.list",
  "agent.read",
  "task.list",
  "task.read",
  "task.start",
  "task.resume",
  "run.start",
  "run.steer",
  "run.interrupt",
  "interaction.resolve",
  "events.replay",
  "snapshot.request",
  "lease.acquire",
  "lease.renew",
  "lease.release",
  "lease.status",
  "notifications.list",
  "notifications.read",
  "config.read",
  "config.update"
] as const;
export type ControlType = (typeof KNOWN_CONTROL_TYPES)[number];

export const KNOWN_EVENT_TYPES = [
  "device.status",
  "runtime.status",
  "agent.snapshot",
  "agent.status",
  "task.snapshot",
  "task.started",
  "task.updated",
  "run.started",
  "run.completed",
  "run.failed",
  "run.interrupted",
  "message.delta",
  "message.completed",
  "reasoning.summary.delta",
  "reasoning.summary.completed",
  "plan.updated",
  "activity.started",
  "activity.updated",
  "activity.completed",
  "interaction.requested",
  "interaction.resolved",
  "file.changed",
  "diff.updated",
  "control.result",
  "lease.changed",
  "history.gap",
  "error"
] as const;
export type EventType = (typeof KNOWN_EVENT_TYPES)[number];

export const ERROR_CODES = [
  "invalid_message",
  "unsupported_protocol",
  "unsupported_control",
  "unauthorized",
  "forbidden",
  "expired",
  "replay",
  "not_found",
  "conflict",
  "rate_limited",
  "payload_too_large",
  "runtime_unavailable",
  "runtime_failed",
  "history_gap",
  "ambiguous",
  "internal"
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export const CONTROL_RESULT_STATES = [
  "received",
  "validated",
  "dispatching",
  "confirmed",
  "rejected",
  "ambiguous"
] as const;
export type ControlResultStatus = (typeof CONTROL_RESULT_STATES)[number];
